# Generated by Django 3.2.9 on 2021-11-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.IntegerField(default=0, verbose_name='Codigo'),
        ),
    ]
