# Generated by Django 3.2.7 on 2021-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superuser',
            field=models.CharField(default=2, max_length=100, verbose_name='superuser'),
            preserve_default=False,
        ),
    ]
